#9SMA Watchlist
SMA9_securities = [#'20210319'
    ["APHA", "NASDAQ", "cannabis", "cannabis", .96],
    ["MSOS", "ARCA", "etf", "cannabis", .98],
    ["BILI", "NASDAQ", "technology", "china", .96],
    ["DQ", "NYSE", "basicMaterials", "china", .95],
    ["IQ", "NASDAQ", "communications", "china", 1.0],
    ["NTES", "NASDAQ", "technology", "china", .97],
    ["CWH", "NYSE", "consumerCyclical", "entertainment", .99],
    ["ZLAB", "NASDAQ", "consumerNonCyclical", "china", .97],
    ["ZTO", "NYSE", "industrial", "china", 1.0],
    ["TDOC", "NYSE", "technology", "software", .99],
    ["BIDU", "NASDAQ", "communications", "china", .99],
    ["IRDM", "NASDAQ", "communications", "telecommunications", .98],
    ["DDD", "NYSE", "technology", "computers", 1.0],
    ["IBB", "NASDAQ", "etf", "biotechnology", .97],
    ["EBAY", "NASDAQ", "communications", "internet", .97],
    ["FCEL", "NASDAQ", "energy", "alternateEnergy", .9],
    ["MJ", "ARCA", "etf", "cannabis", .95],
    ["TLRY", "NASDAQ", "cannabis", "cannabis", .9],
    ["UUUU", "AMEX", "uranium", "uranium", 1.02],
    ["CCJ", "NYSE", "uranium", "uranium", 1.02],
    ["RIOT", "NASDAQ", "blockchain", "blockchain", .91],
    ["PINS", "NYSE", "communications", "internet", .93],
    ["CGC", "NASDAQ", "cannabis", "cannabis", .98],
    ["DOYU", "NASDAQ", "technology", "china", 1.0],
]

#20SMA Watchlist
SMA20_securities = [#'20210319'
    ["ACB", "NYSE", "cannabis", "cannabis", .99],
    ["GRWG", "NASDAQ", "cannabis", "cannabis", .99],
    ["USO", "ARCA", "etf", "energy", 1.00],
    ["SRAC", "NASDAQ", "cannabis", "cannabis", .99],
    ["ONEM", "NASDAQ", "technology", "software", .97],
    ["MGNI", "NASDAQ", "communications", "internet", .92],
    ["IWM", "ARCA", "etf", "stock", .99],
    ["BABA", "NYSE", "communications", "china", 1.0],
    ["FXI", "ARCA", "etf", "china", 1.0],
    ["JMIA", "NYSE", "communications", "china", .90],
    ["VFF", "NASDAQ", "cannabis", "cannabis", .96],
    ["CRON", "NASDAQ", "cannabis", "cannabis", 1.0],
    ["MARA", "NASDAQ", "blockchain", "blockchain", .95],
    ["EEM", "ARCA", "etf", "china", .98],
    ["FVRR", "NYSE", "communications", "internet", .94],
    ["ROKU", "NASDAQ", "communications", "internet", .96],
    ["SPY", "ARCA", "etf", "stock", .96],
    ["XRT", "ARCA", "etf", "retail", .96],
    ["VIPS", "NYSE", "communications", "china", .96],
    ["PYPL", "NASDAQ", "technology", "software", .99],
    ["APPS", "NASDAQ", "technology", "software", .94],
    ["PENN", "NASDAQ", "consumerCyclical", "entertainment", .97],
    ["MELI", "NASDAQ", "communications", "internet", .96],
    ["PBW", "ARCA", "etf", "alternateEnergy", .94],
    ["ICLN", "NASDAQ", "etf", "alternateEnergy", .95],
    ["SPWR", "NASDAQ", "energy", "alternateEnergy", .98],
    ["ARKK", "ARCA", "etf", "software", .98],
    ["IWB", "ARCA", "etf", "stock", .97],
    ["YOLO", "ARCA", "etf", "cannabis", 1.0],
    ["THCX", "ARCA", "etf", "cannabis", .98],
    ["MAXR", "NYSE", "communications", "telecommunications", .89],
    ["DE", "NYSE", "industrial", "machinery", .98],
    ["AAPL", "NASDAQ", "technology", "computers", .96],
    ["JPM", "NYSE", "financial", "financial", .96],
    ["GPS", "NYSE", "consumerCyclical", "retail", .96],
    ["LOW", "NYSE", "consumerCyclical", "homeBuilders", .98],
    ["QQQ", "NYSE", "etf", "technology", .99],
    ["SNAP", "NYSE", "communications", "internet", .94],
    ["Z", "NASDAQ", "communications", "internet", .93],
    ["NIO", "NYSE", "consumerCyclical", "china", .83],
    ["PDD", "NASDAQ", "communications", "china", .96],
    ["SE", "NYSE", "technology", "software", .91],
    ["IIPR", "NYSE", "financial", "financial", .92],
    ["MDB", "NASDAQ", "technology", "software", .89],
    ["AMZN", "NASDAQ", "communications", "fang", .99],
]

# 50SMA Watchlist
SMA50_securities_A = [#'20210416'
    ["SPCE", "NYSE", "technology", "auto", .96],
    ["RIO", "NYSE", "basicMaterials", "mining", .98],
    ["BHP", "NYSE", "uranium", "uranium", .91],
    ["CHWY", "NYSE", "communications", "internet", .95],
    ["MLM", "NYSE", "industrial", "homeBuilders", .98],
    ["TAN", "ARCA", "etf", "alternateEnergy", 1.02],
    ["NXPI", "NASDAQ", "technology", "semiconductors", .98],
    ["SLV", "ARCA", "preciousMetals", "silver", .98],
    ["CSIQ", "NASDAQ", "energy", "alternateEnergy", .98],
    ["DECK", "NYSE", "consumerCyclical", "retail", .95],
    ["FSLR", "NASDAQ", "energy", "alternateEnergy", .99],
    ["XLF", "ARCA", "etf", "financial", .98],
    ["CRWD", "NASDAQ", "technology", "cybersecurity", .90],
    ["PTON", "NASDAQ", "consumerCyclical", "entertainment", .89],
    ["XLE", "ARCA", "etf", "energy", .98],
    ["TSLA", "NASDAQ", "technology", "auto", .95],
    ["CAT", "NYSE", "industrial", "machinery", 1.01],
    ["TGT", "NYSE", "consumerCyclical", "retail", .99],
    ["TWLO", "NYSE", "technology", "software", .97],
    ["INTU", "NASDAQ", "technology", "software", .95],
    ["GOOGL", "NASDAQ", "communications", "fang", .975],
    ["FTCH", "NYSE", "communications", "internet", .87],
    ["XLK", "ARCA", "etf", "technology", 1.02],
    ["NVDA", "NASDAQ", "technology", "semiconductors", .94],
    ["TTD", "NASDAQ", "technology", "software", .9],
    ["TWTR", "NYSE", "communications", "internet", .92],
    ["MRNA", "NASDAQ", "consumerNonCyclical", "biotechnology", .95],
]

SMA50_securities_B = [#'20210521'
    ["SMH", "NASDAQ", "etf", "semiconductors", .98],
    ["FUTU", "NASDAQ", "financial", "china", .96],
    ["KWEB", "ARCA", "etf", "china", .96],
    ["MCHI", "NASDAQ", "etf", "china", .97],
    ["LRCX", "NASDAQ", "technology", "semiconductors", .97],
    ["ENPH", "NASDAQ", "energy", "alternateEnergy", .96],
    ["NET", "NYSE", "technology", "software", .87],
    ["IGV", "BATS", "etf", "software", .98],
    ["OKTA", "NASDAQ", "technology", "software", .96],
    ["BZH", "NYSE", "consumerCyclical", "homeBuilders", .96],
    ["ZM", "NASDAQ", "technology", "software", .93],
]

SMA50_securities_C = [#'20210618'
    ["NIU", "NASDAQ", "consumerCyclical", "china", .9],
    ["KLAC", "NASDAQ", "technology", "semiconductors", .96],
    ["VNET", "NASDAQ", "communications", "china", .96],
    ["PLUG", "NASDAQ", "energy", "alternateEnergy", .98],
    ["ETSY", "NASDAQ", "communications", "internet", .9],
    ["SQ", "NYSE", "technology", "software", .93],
    ["XHB", "ARCA", "etf", "homeBuilders", .99],
    ["TEAM", "NASDAQ", "technology", "software", .94],
    ["SEDG", "NASDAQ", "energy", "alternateEnergy", .90],
    ["JKS", "NYSE", "energy", "china", .90],
    ["HTHT", "NASDAQ", "consumerCyclical", "china", .93],

]
# 200SMA Watchlist
SMA200_securities = [#'20210618'
    ["DIA", "ARCA", "etf", "stock", 1.0],
    ["ADBE", "NASDAQ", "technology", "software", .87],
    ["COST", "ARCA", "consumerCyclical", "retail", .98],
    ["UNP", "NYSE", "industrial", "transportation", .99],
    ["AMD", "NASDAQ", "technology", "semiconductors", .98],
]

# Bollinger Band Watchlist (ALL)
BB_securities = [
    ["APHA", "NASDAQ", "cannabis", "cannabis", .96],#300; Exclude 200SMA
    ["ACB", "NYSE", "cannabis", "cannabis", .99],#292; Exclude 200SMA
    ["GRWG", "NASDAQ", "cannabis", "cannabis", .99],#290; Exclude 200SMA
    ["USO", "ARCA", "etf", "energy", 1.00],#289; Exclude 200SMA
    ["OIH", "ARCA", "etf", "energy"],#285; Exclude 200SMA
    ["SMH", "NASDAQ", "etf", "semiconductors", .98],#283; Exclude 200SMA
    ["SRAC", "NASDAQ", "cannabis", "cannabis", .99],#271; Exclude 200SMA
    ["ONEM", "NASDAQ", "technology", "software", .97],#249; Exclude 200SMA
    ["MGNI", "NASDAQ", "communications", "internet", .92],#159; Exclude 50SMA 200SMA
    ["MSOS", "ARCA", "etf", "cannabis", .98],#100; 40 days, only include 9SMA and 20SMA
    ["IWM", "ARCA", "etf", "stock", .99],
    ["BABA", "NYSE", "communications", "china", 1.0],
    ["BILI", "NASDAQ", "technology", "china", .96],
    ["DQ", "NYSE", "basicMaterials", "china", .95],
    ["FUTU", "NASDAQ", "financial", "china", .96],
    ["FXI", "ARCA", "etf", "china", 1.0],
    ["IQ", "NASDAQ", "communications", "china", 1.0],
    ["JMIA", "NYSE", "communications", "china", .90],
    ["KWEB", "ARCA", "etf", "china", .96],
    ["MCHI", "NASDAQ", "etf", "china", .97],
    ["NIU", "NASDAQ", "consumerCyclical", "china", .9],
    ["NTES", "NASDAQ", "technology", "china", .97],
    ["CWH", "NYSE", "consumerCyclical", "entertainment", .99],
    ["ZLAB", "NASDAQ", "consumerNonCyclical", "china", .97],
    ["ZTO", "NYSE", "industrial", "china", 1.0],
    ["LRCX", "NASDAQ", "technology", "semiconductors", .97],
    ["KLAC", "NASDAQ", "technology", "semiconductors", .96],
    ["TDOC", "NYSE", "technology", "software", .99],
    ["BIDU", "NASDAQ", "communications", "china", .99],
    ["SPCE", "NYSE", "technology", "auto", .96],
    ["IRDM", "NASDAQ", "communications", "telecommunications", .98],
    ["DDD", "NYSE", "technology", "computers", 1.0],
    ["IBB", "NASDAQ", "etf", "biotechnology", .97],
    ["VFF", "NASDAQ", "cannabis", "cannabis", .96],
    ["CRON", "NASDAQ", "cannabis", "cannabis", 1.0],
    ["RIO", "NYSE", "basicMaterials", "mining", .98],
    ["BHP", "NYSE", "uranium", "uranium", .91],
    ["DIA", "ARCA", "etf", "stock", 1.0],
    ["EBAY", "NASDAQ", "communications", "internet", .94],
    ["CHWY", "NYSE", "communications", "internet", .95],
    ["MARA", "NASDAQ", "blockchain", "blockchain", .95],
    ["EEM", "ARCA", "etf", "china", .98],
    ["FVRR", "NYSE", "communications", "internet", .94],
    ["VNET", "NASDAQ", "communications", "china", .96],
    ["FCEL", "NASDAQ", "energy", "alternateEnergy", .9],
    ["ROKU", "NASDAQ", "communications", "internet", .96],
    ["SPY", "ARCA", "etf", "stock", .96],
    ["XRT", "ARCA", "etf", "retail", .96],
    ["VIPS", "NYSE", "communications", "china", .96],
    ["PLUG", "NASDAQ", "energy", "alternateEnergy", .98],
    ["MLM", "NYSE", "industrial", "homeBuilders", .98],
    ["TAN", "ARCA", "etf", "alternateEnergy", 1.02],
    ["PYPL", "NASDAQ", "technology", "software", .99],
    ["APPS", "NASDAQ", "technology", "software", .94],
    ["PENN", "NASDAQ", "consumerCyclical", "entertainment", .97],
    ["MELI", "NASDAQ", "communications", "internet", .96],
    ["ENPH", "NASDAQ", "energy", "alternateEnergy", .96],
    ["PBW", "ARCA", "etf", "alternateEnergy", .94],
    ["ICLN", "NASDAQ", "etf", "alternateEnergy", .95],
    ["SPWR", "NASDAQ", "energy", "alternateEnergy", .98],
    ["NXPI", "NASDAQ", "technology", "semiconductors", .98],
    ["ARKK", "ARCA", "etf", "software", .98],
    ["IWB", "ARCA", "etf", "stock", 97],
    ["YOLO", "ARCA", "etf", "cannabis", 1.0],
    ["THCX", "ARCA", "etf", "cannabis", .98],
    ["MJ", "ARCA", "etf", "cannabis", .95],
    ["TLRY", "NASDAQ", "cannabis", "cannabis", .9],
    ["MAXR", "NYSE", "communications", "telecommunications", .89],
    ["DE", "NYSE", "industrial", "machinery", .98],
    ["SLV", "ARCA", "preciousMetals", "silver", .98],
    ["AAPL", "NASDAQ", "technology", "computers", .96],
    ["CSIQ", "NASDAQ", "energy", "alternateEnergy", .98],
    ["UUUU", "AMEX", "uranium", "uranium", 1.02],
    ["JPM", "NYSE", "financial", "financial", .96],
    ["CCJ", "NYSE", "uranium", "uranium", 1.02],
    ["RIOT", "NASDAQ", "blockchain", "blockchain", .91],
    ["DECK", "NYSE", "consumerCyclical", "retail", .95],
    ["FSLR", "NASDAQ", "energy", "alternateEnergy", .99],
    ["XLF", "ARCA", "etf", "financial", .98],
    ["ETSY", "NASDAQ", "communications", "internet", .9],
    ["GPS", "NYSE", "consumerCyclical", "retail", .96],
    ["LOW", "NYSE", "consumerCyclical", "homeBuilders", .98],
    ["CRWD", "NASDAQ", "technology", "cybersecurity", .90],
    ["NET", "NYSE", "technology", "software", .87],
    ["PINS", "NYSE", "communications", "internet", .93],
    ["PTON", "NASDAQ", "consumerCyclical", "entertainment", .89],
    ["XLE", "ARCA", "etf", "energy", .98],
    ["TSLA", "NASDAQ", "technology", "auto", .95],
    ["QQQ", "NYSE", "etf", "technology", .99],
    ["CAT", "NYSE", "industrial", "machinery", 1.01],
    ["SNAP", "NYSE", "communications", "internet", .94],
    ["SQ", "NYSE", "technology", "software", .93],
    ["TGT", "NYSE", "consumerCyclical", "retail", .99],
    ["TWLO", "NYSE", "technology", "software", .97],
    ["XHB", "ARCA", "etf", "homeBuilders", .99],
    ["Z", "NASDAQ", "communications", "internet", .93],
    ["NIO", "NYSE", "consumerCyclical", "china", .83],
    ["PDD", "NASDAQ", "communications", "china", .96],
    ["IGV", "BATS", "etf", "software", .98],
    ["TEAM", "NASDAQ", "technology", "software", .94],
    ["SEDG", "NASDAQ", "energy", "alternateEnergy", .90],
    ["INTU", "NASDAQ", "technology", "software", .95],
    ["GOOGL", "NASDAQ", "communications", "fang", .975],
    ["OKTA", "NASDAQ", "technology", "software", .96],
    ["SE", "NYSE", "technology", "software", .91],
    ["CGC", "NASDAQ", "cannabis", "cannabis", .98],
    ["IIPR", "NYSE", "financial", "financial", .92],
    ["FTCH", "NYSE", "communications", "internet", .87],
    ["MDB", "NASDAQ", "technology", "software", .89],
    ["BZH", "NYSE", "consumerCyclical", "homeBuilders", .96],
    ["XLK", "ARCA", "etf", "technology", 1.02],
    ["ADBE", "NASDAQ", "technology", "software", .87],
    ["COST", "ARCA", "consumerCyclical", "retail", .98],
    ["NVDA", "NASDAQ", "technology", "semiconductors", .94],
    ["TTD", "NASDAQ", "technology", "software", .9],
    ["TWTR", "NYSE", "communications", "internet", .92],
    ["UNP", "NYSE", "industrial", "transportation", .99],
    ["DOYU", "NASDAQ", "technology", "china", 1.0],
    ["JKS", "NYSE", "energy", "china", .90],
    ["HTHT", "NASDAQ", "consumerCyclical", "china", .93],
    ["AMZN", "NASDAQ", "communications", "fang", .99],
    ["ZM", "NASDAQ", "technology", "software", .93],
    ["MRNA", "NASDAQ", "consumerNonCyclical", "biotechnology", .95],
    ["AMD", "NASDAQ", "technology", "semiconductors", .98],
]
